### ISSUE TITLE
Deployment referred for live stream but no link provided

### ISSUE THREAD

**Issue by aukhanee** [adl1995/leaf-classification#1]
The README suggests that for running the code on live stream, we should refer to deployment code or markdown. But it is not available in the repo. Please update.

**Comment by adl1995** [comment]
Sorry, the README.md file was extended from a template, some parts of which don't apply to this repository. I have updated the file, and removed the part on code deployment.

Where do you plan on deploying this? I tested this on a Google Cloud machine, and for that you just need to follow similar steps as you would on your local system.

**Comment by aukhanee** [comment]
Actually, I have a course project and was looking to deploy it on Nvidia TK1.

**Comment by adl1995** [comment]
Not relevant to the project.
